# Stage 1: Build
FROM --platform=linux/amd64 node:alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps true
COPY . .
RUN npm run build

# Stage 2: Run
FROM --platform=linux/amd64 nginx:alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
